/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mode-select`; params?: Router.UnknownInputParams; } | { pathname: `/pin-setup`; params?: Router.UnknownInputParams; } | { pathname: `/pin`; params?: Router.UnknownInputParams; } | { pathname: `/build-status`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/functions/build-webhook/index`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/functions/request-build/index`; params?: Router.UnknownInputParams; } | { pathname: `/brand-setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/laporan` | `/laporan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/riwayat` | `/riwayat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tarik` | `/tarik`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transfer` | `/transfer`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/mode-select`; params?: Router.UnknownOutputParams; } | { pathname: `/pin-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/pin`; params?: Router.UnknownOutputParams; } | { pathname: `/build-status`; params?: Router.UnknownOutputParams; } | { pathname: `/../supabase/functions/build-webhook/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../supabase/functions/request-build/index`; params?: Router.UnknownOutputParams; } | { pathname: `/brand-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/laporan` | `/laporan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/riwayat` | `/riwayat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tarik` | `/tarik`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/transfer` | `/transfer`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/mode-select${`?${string}` | `#${string}` | ''}` | `/pin-setup${`?${string}` | `#${string}` | ''}` | `/pin${`?${string}` | `#${string}` | ''}` | `/build-status${`?${string}` | `#${string}` | ''}` | `/../supabase/functions/build-webhook/index${`?${string}` | `#${string}` | ''}` | `/../supabase/functions/request-build/index${`?${string}` | `#${string}` | ''}` | `/brand-setup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/laporan${`?${string}` | `#${string}` | ''}` | `/laporan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/riwayat${`?${string}` | `#${string}` | ''}` | `/riwayat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tarik${`?${string}` | `#${string}` | ''}` | `/tarik${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/transfer${`?${string}` | `#${string}` | ''}` | `/transfer${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mode-select`; params?: Router.UnknownInputParams; } | { pathname: `/pin-setup`; params?: Router.UnknownInputParams; } | { pathname: `/pin`; params?: Router.UnknownInputParams; } | { pathname: `/build-status`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/functions/build-webhook/index`; params?: Router.UnknownInputParams; } | { pathname: `/../supabase/functions/request-build/index`; params?: Router.UnknownInputParams; } | { pathname: `/brand-setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/laporan` | `/laporan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/riwayat` | `/riwayat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tarik` | `/tarik`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transfer` | `/transfer`; params?: Router.UnknownInputParams; };
    }
  }
}
